spring:


  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 7001
