spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recommendationdb
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: 
      - optional:configserver:http://localhost:7777/

server:
  port: 7003
